---
- name: Deploy amd start Apache HTTPD service
  hosts: appserver
  vars: 
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: python-httplib2
    rule: http

  tasks:
    - name: Required packages are installed and up to date
      yum:
        name:
          - "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
          - "{{ python_pkg }}"
        state: latest

    - name: The {{ firewall_service }} service is started and enabled
      service:
        name: "{{ firewall_service }}"
        state: started
        enabled: true

    - name: The {{ web_service }} service is started and enabled
      service: 
        name: "{{ web_service }}"
        state: started
        enabled: true


    - name: Web content is in place
      copy:
        content: "Example web content"
        dest: /var/www/html/index.html

    - name: The firewall port for {{ rule }} is open
      firewalld: 
        service: "{{ rule }}" 
        immediate: true
        permanent: true
        state: enabled

    
- name: Verify the apache service
  hosts: localhost
  become: false
  
  tasks:
    - name: Ensure the webserver is reachable
      uri:
        url: http://serverb.lab.example.com
        status_code: 200




